insert into custdetail values(200,'Uverse Internet', 50.00, 'Uverse 30mbs internet');
insert into custdetail values(200,'Direct TV', 60.00, 'Premium Package');
insert into custdetail values(200,'Go Phone', 30.00, 'standard plan,no data');
insert into custdetail values(201,'Cell Phone', 45.00, 'Android Droid Xt');
insert into custdetail values(201,'Direct TV', 50.00, 'Standard Package');
insert into custdetail values(201,'Voip Phone', 45.00, 'Umlimited US and Canada');
insert into custdetail values(202,'Cell Phone', 55.00, 'Iphone 7');
insert into custdetail values(202,'Uverse TV', 70.00, 'Premium Package');
insert into custdetail values(203,'Uverse TV', 70.00, 'Premium Package');
insert into custdetail values(204,'Direct TV', 50.00, 'Standard Package');
insert into custdetail values(205,'Go Phone', 30.00, 'Standard Plan no data');
insert into custdetail values(206,'Cell Phone', 90.00, 'Iphone 6');
